final

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -61,8 +61,8 @@ commands:
           name: Revert migrations
           when: on_fail
           command: |
-            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-            SUCCESS=$(curl --insecure "https://kvdb.io/Fip8CaTDwXQvJL62wFgq3e/migration_<<parameters.workflow_id>>")
+            # Set up kvdb.io accoun and Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+            SUCCESS=$(curl --insecure "https://kvdb.io/*bucket-id*/migration_<<parameters.workflow_id>>")
             if(( $SUCCESS==1 )); 
             then
               cd ~/project/backend
@@ -228,8 +228,8 @@ jobs:
     steps:
       - checkout
       - add_ssh_keys:
-          fingerprints:
-            - "f1:87:1a:55:94:50:61:0e:12:70:a1:c1:5a:3f:64:a8"
+          fingerprints: #add ssh key to circleCI, copy fingerprint generated.
+            - "f1:87:1a:55:94:50:61:0e:12:70:a1:c1:5a:3f"
       - attach_workspace:
           at: ~/
 
@@ -262,9 +262,9 @@ jobs:
           command: |
             if [ $? -eq 0 ]
             then
-              echo "Migration has been executed successfully. " > migrations_dump.txt && curl --insecure https://kvdb.io/Fip8CaTDwXQvJL62wFgq3e/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
+              echo "Migration has been executed successfully. " > migrations_dump.txt && curl --insecure https://kvdb.io/*bucket-id*/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
             else
-              echo "You failed this time. " && exit 1 && curl --insecure https://kvdb.io/Fip8CaTDwXQvJL62wFgq3e/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '0'
+              echo "You failed this time. " && exit 1 && curl --insecure https://kvdb.io/*bucket-id*/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '0'
             fi
             cat migrations_dump.txt
       - destroy-environment
@@ -278,7 +278,7 @@ jobs:
       - checkout
       - add_ssh_keys:
           fingerprints:
-            - "f1:87:1a:55:94:50:61:0e:12:70:a1:c1:5a:3f:64:a8"
+            - "f1:1a:55:94:50:61:0e:12:70:a1:c1:5a:3f"
       - attach_workspace:
           at: ~/
 
@@ -318,7 +318,7 @@ jobs:
       - checkout
       - add_ssh_keys:
           fingerprints:
-            - "f1:87:1a:55:94:50:61:0e:12:70:a1:c1:5a:3f:64:a8"
+            - "f1:1a:55:94:50:61:0e:12:70:a1:c1:5a:3f"
       - attach_workspace:
           at: ~/
       - install_nodejs
@@ -396,7 +396,7 @@ jobs:
             --query "Exports[?Name=='WorkflowID'].Value" \
             --no-paginate --output text)
             echo "Old Workflow ID: $OLD_WORKFLOW_ID"
-            curl --insecure https://kvdb.io/Fip8CaTDwXQvJL62wFgq3e/old_workflow_id -d "${OLD_WORKFLOW_ID}"
+            curl --insecure https://kvdb.io/*bucket-id*/old_workflow_id -d "${OLD_WORKFLOW_ID}"
       - run:
           name: Update cloudfront distribution
           command: |
@@ -421,12 +421,12 @@ jobs:
                 --query "StackSummaries[*].StackName" \
                 --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
             echo Stack names: "${STACKS[@]}"
-            export OldWorkflowID=$(curl --insecure https://kvdb.io/Fip8CaTDwXQvJL62wFgq3e/old_workflow_id)
+            export OldWorkflowID=$(curl --insecure https://kvdb.io/*bucket-id*/old_workflow_id)
             echo Old Workflow ID: $OldWorkflowID
       - run:
           name: Remove old stacks and files
           command: |
-            export OldWorkflowID=$(curl --insecure https://kvdb.io/Fip8CaTDwXQvJL62wFgq3e/old_workflow_id)
+            export OldWorkflowID=$(curl --insecure https://kvdb.io/*bucket-id*/old_workflow_id)
             echo Old Workflow ID: $OldWorkflowID
 
             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
